spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/GRAD
    username: dbadmin
    password: dbadmin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5969
        expiration: 18000000 # 5 hours in milliseconds
        refresh-expiration: 604800000 # 7 days in milliseconds
    url: http://localhost:5173