spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/GRAD}
    username: ${SPRING_DATASOURCE_USERNAME:dbadmin}
    password: ${SPRING_DATASOURCE_PASSWORD:dbadmin}
    driver-class-name: org.postgresql.Driver
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    username: ${SPRING_REDIS_USERNAME:dbadmin}
    password: ${SPRING_REDIS_PASSWORD:dbadmin}
    database: ${SPRING_REDIS_DATABASE:0}
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    security:
      jwt:
        secret-key: ${SPRING_APPLICATION_SECURITY_JWT_SECRET_KEY:}
        expiration: ${SPRING_APPLICATION_SECURITY_JWT_EXPIRATION:3600000}
      refresh-token:
        pepper: ${SECURITY_REFRESH_TOKEN_PEPPER:}
        expiration: ${SPRING_APPLICATION_SECURITY_JWT_REFRESH_EXPIRATION:604800000}
    url: ${SPRING_APPLICATION_URL:http://localhost:3000}
