server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/GRAD}
    username: ${SPRING_DATASOURCE_USERNAME:dbadmin}
    password: ${SPRING_DATASOURCE_PASSWORD:dbadmin}
    driver-class-name: org.postgresql.Driver
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    username: ${SPRING_REDIS_USERNAME:dbadmin}
    password: ${SPRING_REDIS_PASSWORD:dbadmin}
    database: ${SPRING_REDIS_DATABASE:0}
    ssl:
      enabled: ${SPRING_DATA_REDIS_SSL_ENABLED:false}
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  exam-datasource:
    url: ${EXAM_DATASOURCE_URL:jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true}
    username: ${EXAM_DATASOURCE_USERNAME:sa}
    password: ${EXAM_DATASOURCE_PASSWORD:P@ssw0rd123!}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  application:
    gemini:
      api-key: ${GEMINI_API_KEY:}
    security:
      jwt:
        secret-key: ${SPRING_APPLICATION_SECURITY_JWT_SECRET_KEY:}
        expiration: ${SPRING_APPLICATION_SECURITY_JWT_EXPIRATION:3600000}
      refresh-token:
        pepper: ${SECURITY_REFRESH_TOKEN_PEPPER:}
        expiration: ${SPRING_APPLICATION_SECURITY_JWT_REFRESH_EXPIRATION:604800000}
    url: ${SPRING_APPLICATION_URL:http://localhost:3000}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
  logging:
  file:
    name: backend.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
      clean-history-on-start: true
      max-history: 1
      max-file-size: 10MB
