server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    
  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}
    username: ${SPRING_REDIS_USERNAME}
    password: ${SPRING_REDIS_PASSWORD}
    database: ${SPRING_REDIS_DATABASE}
    ssl:
      enabled: ${SPRING_DATA_REDIS_SSL_ENABLED:false} 
      
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  exam-datasource:
    url: ${EXAM_DATASOURCE_URL}
    username: ${EXAM_DATASOURCE_USERNAME}
    password: ${EXAM_DATASOURCE_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  application:
    gemini:
      api-key: ${GEMINI_API_KEY}
      model: ${GEMINI_MODEL:gemini-2.5-flash-lite}
    security:
      jwt:
        secret-key: ${SPRING_APPLICATION_SECURITY_JWT_SECRET_KEY}
        expiration: ${SPRING_APPLICATION_SECURITY_JWT_EXPIRATION}
      refresh-token:
        pepper: ${SECURITY_REFRESH_TOKEN_PEPPER}
        expiration: ${SPRING_APPLICATION_SECURITY_JWT_REFRESH_EXPIRATION}
    url: ${SPRING_APPLICATION_URL}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}