spring:
  application:
    name: graduation-project-be
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  liquibase:
    change-log: classpath:db/changelog/grad-changelog-master.yaml

app:
  upload:
    pdf-dir: ${APP_UPLOAD_PDF_DIR:uploads/exams/pdf}

