package graduation_project_be.application.codes;


public enum Code {
    VALIDATION_FAILED,
    INTERNAL_SERVER_ERROR,
    JWT_TOKEN_INVALID,
    STATUS_NOT_FOUND,
    ROLE_NOT_FOUND,
    INVALID_FORMAT,
    INVALID_BUSINESS_RULE,
    NOT_FOUND,
    BAD_REQUEST,
    UNAUTHORIZED,
    CONFLICT,
    OPERATION_FAILED,
    INTERNAL_ERROR,
    DATABASE_ERROR,
    OK,
}
